### ISSUE TITLE
Incompatible with prodigy 1.8

### ISSUE THREAD

**Issue by gnestor** [gnestor/jupyterlab-prodigy#1]
After upgrading to prodigy 1.8.0 and above, I get the following error:

```bash
$ prodigy ner.teach my_set en_core_web_sm news_headlines.jsonl
Traceback (most recent call last):
  File "/Users/grant/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/grant/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/prodigy/__main__.py", line 380, in <module>
    controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 212, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "/Users/grant/anaconda/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/prodigy/recipes/ner.py", line 120, in teach
    nlp = spacy.load(spacy_model)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/util.py", line 131, in load_model
    return load_model_from_package(name, **overrides)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/util.py", line 152, in load_model_from_package
    return cls.load(**overrides)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/language.py", line 791, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/util.py", line 630, in from_disk
    reader(path / key)
  File "/Users/grant/anaconda/lib/python3.6/site-packages/spacy/language.py", line 781, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 437, in spacy.tokenizer.Tokenizer.from_bytes
  File "/Users/grant/anaconda/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/grant/anaconda/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/grant/anaconda/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/grant/anaconda/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/grant/anaconda/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Users/grant/anaconda/lib/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/Users/grant/anaconda/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 257
```

**Comment by ines** [comment]
Ah, the problem here is that you need to update your spaCy models – Prodigy v1.8 uses the latest version of spaCy, and the statistical models have been updated.

You can run the following commands to find out what needs to be updated and what commands to run:

```bash
python -m spacy validate
```

**Comment by gnestor** [comment]
That fixed it! Thanks @ines!
